### ISSUE TITLE
Przenies prosze cala logike walki do klasy FightService

### ISSUE THREAD

**Issue by bulakowy** [danieltendaj/arena#1]
https://github.com/danieltendaj/arena/blob/c324cf8041a2c2ef738d661c0f64c107ba56c7d1/src/main/java/com/stepstone/training/arena/ArenaApplication.java#L18

**Comment by danieltendaj** [comment]
Dopiero teraz zauważyłem issue, ale w sumie zrealizowałem je w commicie: https://github.com/danieltendaj/arena/commit/a6757658a8fdd97ca44d4a139494f762545383d6
